// Next.js modules
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

// Styles
import styles from "@/styles/Home.module.css";

// Components
import NavBar from "@/components/shared/NavMenu";
import Header from "@/components/homePage/Header";
import HowItWorks from "@/components/homePage/HowItWorks";
import HowHelp from "@/components/homePage/HowHelp";
import Contact from "@/components/homePage/Contact";
import Footer from "@/components/shared/Footer";
import { useEffect } from "react";
import { hasAccesss } from "@/utils/accessControl";

export default function Home() {
  useEffect(() => {
   
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <NavBar />
        <Header />
        <HowItWorks />
        <HowHelp />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
